package com.yul.pojo;

import java.util.Date;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_student.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_student.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_student.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_student.major_id
     *
     * @mbggenerated
     */
    private String majorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_student.class_id
     *
     * @mbggenerated
     */
    private String classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_student.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_student.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_student.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_student.birth
     *
     * @mbggenerated
     */
    private Date birth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_student.id
     *
     * @return the value of pm_student.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_student.id
     *
     * @param id the value for pm_student.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_student.name
     *
     * @return the value of pm_student.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_student.name
     *
     * @param name the value for pm_student.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_student.password
     *
     * @return the value of pm_student.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_student.password
     *
     * @param password the value for pm_student.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_student.major_id
     *
     * @return the value of pm_student.major_id
     *
     * @mbggenerated
     */
    public String getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_student.major_id
     *
     * @param majorId the value for pm_student.major_id
     *
     * @mbggenerated
     */
    public void setMajorId(String majorId) {
        this.majorId = majorId == null ? null : majorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_student.class_id
     *
     * @return the value of pm_student.class_id
     *
     * @mbggenerated
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_student.class_id
     *
     * @param classId the value for pm_student.class_id
     *
     * @mbggenerated
     */
    public void setClassId(String classId) {
        this.classId = classId == null ? null : classId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_student.type
     *
     * @return the value of pm_student.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_student.type
     *
     * @param type the value for pm_student.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_student.address
     *
     * @return the value of pm_student.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_student.address
     *
     * @param address the value for pm_student.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_student.phone
     *
     * @return the value of pm_student.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_student.phone
     *
     * @param phone the value for pm_student.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_student.birth
     *
     * @return the value of pm_student.birth
     *
     * @mbggenerated
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_student.birth
     *
     * @param birth the value for pm_student.birth
     *
     * @mbggenerated
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }
}